### PR TITLE
2021-3.1 envs

### PR DESCRIPTION
**Pull request by mrakitin**
Adding an extra package [`dictdiffer`](https://anaconda.org/conda-forge/dictdiffer).

```diff
$ diff envs/nsls2-collection-2021-3.0-py37-env.yml envs/nsls2-collection-2021-3.1-py37-env.yml 
1c1
< name: nsls2-collection-2021-3.0-py37
---
> name: nsls2-collection-2021-3.1-py37
30a31
>   - dictdiffer
```

```diff
$ diff envs/nsls2-collection-2021-3.0-py39-env.yml envs/nsls2-collection-2021-3.1-py39-env.yml 
1c1
< name: nsls2-collection-2021-3.0-py39
---
> name: nsls2-collection-2021-3.1-py39
30a31
>   - dictdiffer
```

```diff
$ diff envs/nsls2-collection-2021-3.1-py37-env.yml envs/nsls2-collection-2021-3.1-py39-env.yml 
1c1
< name: nsls2-collection-2021-3.1-py37
---
> name: nsls2-collection-2021-3.1-py39
10c10
<   - python >=3.7,<3.8
---
>   - python >=3.9,<3.10
```
```

### CODE REVIEW

**Comment by dmgav** [comment]
Could we add `dpcmaps` package. This is analysis software used at HXN and SRX. It is available from conda-forge.

**Comment by mrakitin** [comment]
> Could we add `dpcmaps` package. This is analysis software used at HXN and SRX. It is available from conda-forge.

Added via https://github.com/NSLS-II/conda-pack-template/pull/45/commits/46e145a696f5ce37d4538a7bbf6af57df7c776d5.

**Comment by mrakitin** [comment]
@tacaswell, I added [`cmasher`](https://anaconda.org/conda-forge/cmasher) via 6c81ee9.

**Comment by mrakitin** [comment]
Deposition to Zenodo: https://zenodo.org/record/5802039.

**Pull request merged**
