### PR TITLE
CI: debug info to check /build is mounted

### PR DESCRIPTION
**Pull request by mrakitin**
This update is to fix the CI to produce the artifacts in the `artifacts/` directory (they still have different owner, but it'd not a big deal for now).

### CODE REVIEW

**Review by johngedell — APPROVED** [review]
I looked up sort -u. It's a good solution for sorting the files and sorting and removing adjacent lines. I like it!

**Comment by mrakitin** [comment]
Thanks for checking it, @johngedell! Sometimes, there can be repeating lines, so `sort -u` sorts and outputs the unique lines.

**Review by johngedell — APPROVED** [review]
I am now aware of the difference between ls -la and ls -laF (in terms of the latter listing a long format list of all file types). Makes sense.

I understand the changes with the mounting of the build directory and additions of the repo directory and artifact directory in runner.sh.j2.

Okay. I understand the changes made later in the runner file when using the build and repo directories with export.sh.

**Review by johngedell — COMMENTED** [review]
This addition is straightforward and obvious to me now. We are removing privileges from root and giving it to the user.

**Comment by mrakitin** [comment]
> This addition is straightforward and obvious to me now. We are removing privileges from root and giving it to the user.

Actually, in the running Docker container, the generated files were owned by the `conda` user with the id=9001, so it wasn't possible to add the files to the cloned repo in the CI from the container, which is read-only for non-`runner` users. So, the solution was to create a world-writable `artifacts` directory (with `777`, or `rwxrwxrwx` permissions), and to place the files within the Docker container to that directory, and finally, when the build is over, change the ownership from the "unknown" to the CI environment user (with the id=9001) to the actual user that runs the CI build (`runner`).

**Pull request merged**
